blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussions
    url: https://github.com/devanonitos/docustarter/discussions
    about: Please ask questions or share ideas here instead of creating an issue.

  - name:  ğŸ“ Bug Reports
    url: https://github.com/devanonitos/docustarter/issues
    about: Use this for reproducible bugs or feature requests.

  - name: ğŸ›¡ï¸ Security Issues
    url: https://github.com/devanonitos/docustarter/security/policy
    about: Please report security vulnerabilities here.
